apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: my-apimanager
  # namespace: api-mgmt
spec:
  resourceRequirementsEnabled: true
  system:
    redisPersistentVolumeClaim:
      storageClassName: gp2
    database:
      mysql:
        persistentVolumeClaim:
          storageClassName: gp2
    fileStorage:
      simpleStorageService:
        configurationSecretRef:
          name: aws-auth
      # persistentVolumeClaim:
        # storageClassName: nfs
        # volumeName: <your-nfs-pv>
  backend:
    redisPersistentVolumeClaim:
      storageClassName: gp2
  wildcardDomain: apps.cluster-15d3.sandbox1683.opentlc.com
